[package]
name = "repl-net-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.13"
fixed = "1.29.0"

anyhow = "1.0.99"
bitflags = "2.9.4"
bincode = "1.3.3"
clap = { version = "4.5.47", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
